source "https://rubygems.org"

# Rails framework and essential gems
gem "rails", "~> 7.2.1", ">= 7.2.1.1"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "carrierwave"
gem "devise"
gem "bootstrap", "~> 5.1.3"
gem "sassc-rails"
gem "execjs"


# Uncomment to use Redis in production
# gem "redis", ">= 4.0.1"

# Uncomment for Kredis (higher-level data types in Redis)
# gem "kredis"

# Uncomment for bcrypt (secure password management)
# gem "bcrypt", "~> 3.1.7"

# Timezone data for Windows platforms
gem "tzinfo-data", platforms: %i[mswin mswin64 mingw jruby]

# Performance optimization
gem "bootsnap", require: false

# Uncomment to enable Active Storage image processing
# gem "image_processing", "~> 1.2"

# Development and test gems
group :development, :test do
  gem "debug", platforms: %i[mri mswin mswin64 mingw], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

# Development-only gems
group :development do
  gem "web-console"
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end

# Test-only gems
group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
